import 'package:flutter/material.dart';

class UpcomingProvider with ChangeNotifier {
  final List<Map<String, String>> _arrUpcoming = [
    {
      "image": "assets/img/car1_mybooking.png",
      "carName": "Maruti Swift",
      "model": "(Model Apr 2020)",
      "gear": "Automatic",
      "gearPic": "assets/img/gear_mybooking.png",
      "fuelPic": "assets/img/fuel_mybooking.png",
      "seatPic": "assets/img/seat_mybooking.png",
      "fuel": "Petrol",
      "seat": "7 Seats",
      "pickUpaddress": "Delhi-NCR",
      "pickUpdate": "Mon, 06 Jan 2025",
      "pickUptime": "09:30 AM",
      "dropOffaddress": "Delhi-NCR",
      "dropOffdate": "Mon, 07 Tue 2025",
      "dropOfftime": "11:30 PM",
    },
    {
      "image": "assets/img/car2_mybooking.png",
      "carName": "Maruti Swift",
      "model": "(Model Apr 2020)",
      "gearPic": "assets/img/gear_mybooking.png",
      "fuelPic": "assets/img/fuel_mybooking.png",
      "seatPic": "assets/img/seat_mybooking.png",
      "gear": "Automatic",
      "fuel": "Petrol",
      "seat": "7 Seats",
      "pickUpaddress": "Delhi-NCR",
      "pickUpdate": "Mon, 06 Jan 2025",
      "pickUptime": "09:30 AM",
      "dropOffaddress": "Delhi-NCR",
      "dropOffdate": "Mon, 07 Tue 2025",
      "dropOfftime": "11:30 PM",
    },
    {
      "image": "assets/img/car3_mybooking.png",
      "carName": "Maruti Swift",
      "model": "(Model Apr 2020)",
      "gearPic": "assets/img/gear_mybooking.png",
      "fuelPic": "assets/img/fuel_mybooking.png",
      "seatPic": "assets/img/seat_mybooking.png",
      "gear": "Automatic",
      "fuel": "Petrol",
      "seat": "7 Seats",
      "pickUpaddress": "Delhi-NCR",
      "pickUpdate": "Mon, 06 Jan 2025",
      "pickUptime": "09:30 AM",
      "dropOffaddress": "Delhi-NCR",
      "dropOffdate": "Mon, 07 Tue 2025",
      "dropOfftime": "11:30 PM",
    },
    {
      "image": "assets/img/car4_mybooking.png",
      "carName": "Maruti Swift",
      "model": "(Model Apr 2020)",
      "gearPic": "assets/img/gear_mybooking.png",
      "fuelPic": "assets/img/fuel_mybooking.png",
      "seatPic": "assets/img/seat_mybooking.png",
      "gear": "Automatic",
      "fuel": "Petrol",
      "seat": "7 Seats",
      "pickUpaddress": "Delhi-NCR",
      "pickUpdate": "Mon, 06 Jan 2025",
      "pickUptime": "09:30 AM",
      "dropOffaddress": "Delhi-NCR",
      "dropOffdate": "Mon, 07 Tue 2025",
      "dropOfftime": "11:30 PM",
    },
  ];
  List<Map<String, String>> get arrUpcoming => _arrUpcoming;
}
